remote_theme             : "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
logo                     : "/assets/images/tg_website_icon.png"
title                    : "Tilted Gryphons"
title_separator          : "-"
subtitle                 : "A US-Pagle Alliance Guild"
url                      : https://tilted-gryphons.github.io/
repository               : "Tilted-Gryphons/tilted-gryphons.github.io"
search                   : false

head_scripts:
  - /assets/js/links.js
  
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Reading Files
include:
  - pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "pages"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "sidemenu"

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins (previously gems:)
plugins:
  # Github Pages defaults, can't be disabled!
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # MMistakes Rec
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - Kramdown
  # Extra

# mimic GitHub Pages with --safe
whitelist:
  # Github Pages defaults, can't be disabled!
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # MMistakes Rec
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - Kramdown
  # Extra
