remote_theme             : "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin    : "mint"

# Site Settings
locale                   : "en-US"
title                    : "Tilted Gryphons"
title_separator          : "-"
subtitle                 : "A US-Pagle Alliance Guild"
search                   : false

# Reading Files
include:
  - pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: "sidemenu"

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
